name: "ecart"
version: "1.0.0"

profile: "ecart"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  ecart:
    STAGE:
      +materialized: view
      +persist_docs:
        relation: true
        columns: true

sources:
  +persist_docs:
    relation: true
    columns: true

seeds:
  ecart:
    +persist_docs:
      relation: true
      columns: true
    +schema: DIM
    dim_loinc_answer_list:
      file: dim_loinc_answer_list.csv
    dim_loinc_answer_list_link:
      file: dim_loinc_answer_list_link.csv
    dim_loinc_consumer_name:
      file: dim_loinc_consumer_name.csv
    dim_loinc_document_ontology:
      file: dim_loinc_document_ontology.csv
    dim_loinc_group:
      file: dim_loinc_group.csv
    dim_loinc_group_loinc_terms:
      file: dim_loinc_group_loinc_terms.csv
    dim_loinc_imaging_document_codes:
      file: dim_loinc_imaging_document_codes.csv
    dim_loinc_map_to:
      file: dim_loinc_map_to.csv
    dim_loinc_panels_and_forms:
      file: dim_loinc_panels_and_forms.csv
    dim_loinc_part:
      file: dim_loinc_part.csv
    dim_loinc_part_link_primary:
      file: dim_loinc_part_link_primary.csv
