version: 2

models:
  - name: timeseries_patient_retention
    description: >
      Tracks patient retention over time using a cohort-based approach.
      Includes first encounter dates, follow-ups, and new/returning classification.
    columns:
      - name: encounter_day
        description: The date of the encounter.
        tests:
          - not_null

      - name: cohort_day
        description: The first recorded encounter date per patient (cohort start).
        tests:
          - not_null

      - name: date_index
        description: Days since the patient’s first encounter.
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 0

      - name: new_or_returning
        description: Classification of patient encounter as 'New' (first seen) or 'Returning'.
        tests:
          - not_null
          - accepted_values:
              values: ["New", "Returning"]

      - name: unique_patients
        description: Number of unique patients seen on a given day for a cohort.
        tests:
          - not_null

      - name: total_encounters
        description: Total number of encounters on a given day for a cohort.
        tests:
          - not_null

  - name: kpi_snapshot
    description: >
      Snapshot of core KPIs for the current date. Includes counts of patients,
      encounters, conditions, and the average observation value.
    columns:
      - name: snapshot_date
        description: Date when the snapshot was taken (should equal current_date).
        tests:
          - not_null

      - name: num_patients
        description: Total number of unique patients in the dataset.
        tests:
          - not_null

      - name: num_encounters
        description: Total number of unique patient encounters.
        tests:
          - not_null

      - name: num_conditions
        description: Total number of unique patient conditions.
        tests:
          - not_null

      - name: avg_observation_value
        description: Average numeric value of all patient observations.
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 0

  - name: kpi_weekly
    description: >
      Weekly KPI summary including patient, encounter, observation, and condition counts.
      Also includes week-over-week changes using lag comparisons.
    columns:
      - name: week
        description: Start date of the ISO week.
        tests:
          - not_null
          - unique

      - name: unique_patients
        description: Number of unique patients seen during the week.
        tests:
          - not_null

      - name: patients_vs_prev_week
        description: Change in unique patient count compared to the previous week.

      - name: unique_encounters
        description: Number of unique encounters during the week.
        tests:
          - not_null

      - name: encounters_vs_prev_week
        description: Change in unique encounters compared to the previous week.

      - name: unique_observations
        description: Number of unique observations recorded during the week.
        tests:
          - not_null

      - name: observations_vs_prev_week
        description: Change in unique observations compared to the previous week.

      - name: unique_conditions
        description: Number of unique conditions recorded during the week.
        tests:
          - not_null

      - name: conditions_vs_prev_week
        description: Change in unique conditions compared to the previous week.
